[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rfid"
description = "An Example Project"
version = "1.0"
readme = "README.md"
dependencies = ["paramiko", "sllurp", "keyboard", "pandas", "nicegui", "pyperclip"]